import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const url=Deno.env.get("SUPABASE_URL")??"", service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-taskmap-sync-key, x-taskmap-recovery-token","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const ok=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors});
const bad=(message:string,status=400)=>ok({error:message},status);
type Role="owner"|"editor"|"viewer"; type EType="task"|"task_layout"|"project"|"task_category"|"dev_backlog"|"task_template";
const email=(v:unknown)=>String(v??"").trim().toLowerCase();
function hint(v:string){const [l,d=""]=v.split("@"),[n,...s]=d.split("."); const h=(x:string)=>x.length<=2?`${x[0]??"*"}*`:`${x[0]}***${x.at(-1)}`; return l&&d?`${h(l)}@${h(n)}${s.length?`.`+s.join("."):""}`:"Email configured";}
async function hash(v:string){const a=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(a)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function same(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;}
function secret(){const a=new Uint8Array(32);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");}
function parseKey(v:string|null){const p=(v??"").trim().split(".");if(p.length!==3||p[0]!=="TM1"||!/^[0-9a-f-]{36}$/i.test(p[1])||p[2].length<32)throw new Error("Invalid TaskMap Sync Key");return{id:p[1],secret:p[2]};}
async function workspace(id:string){const{data,error}=await db.from("sync_workspaces").select("id,name,recovery_email_hint,recovery_email_verified_at,pending_recovery_email_hint,created_at,updated_at").eq("id",id).single();if(error||!data)throw new Error("Workspace not found");return data;}
async function authKey(raw:string|null,owner=false){const p=parseKey(raw);const{data,error}=await db.from("sync_workspace_keys").select("workspace_id,id,key_hash,role").eq("id",p.id).is("revoked_at",null).single();if(error||!data)throw new Error("Sync Key not found or revoked");if(!same(await hash(p.secret),String(data.key_hash)))throw new Error("Invalid TaskMap Sync Key");if(owner&&data.role!=="owner")throw new Error("Owner Sync Key required");await db.from("sync_workspace_keys").update({last_used_at:new Date().toISOString()}).eq("id",p.id);return{workspaceId:String(data.workspace_id),keyId:String(data.id),role:data.role as Role,workspace:await workspace(String(data.workspace_id))};}
async function newKey(workspaceId:string,role:Role="owner",label="Primary key"){const id=crypto.randomUUID(),s=secret();const{error}=await db.from("sync_workspace_keys").insert({workspace_id:workspaceId,id,key_hash:await hash(s),role,label:label.slice(0,80)});if(error)throw error;return{syncKey:`TM1.${id}.${s}`,keyId:id,role,label};}
async function recoveryUser(token:string|null){if(!token)throw new Error("Recovery email verification is required");const{data,error}=await db.auth.getUser(token);if(error||!data.user?.email)throw new Error("Recovery link is invalid or expired");return data.user;}
async function snap(workspaceId:string,deviceId:string,item:any){const payload=item.payload&&typeof item.payload==="object"?item.payload:null;const ts=typeof payload?.updatedAt==="string"?payload.updatedAt:typeof payload?.createdAt==="string"?payload.createdAt:new Date().toISOString();const t={id:crypto.randomUUID(),entityType:item.entityType,entityId:item.entityId,actionType:"CLOUD_BOOTSTRAP",groupId:null,deviceId,clientTimestamp:ts,baseRevision:0,resultRevision:Number(payload?.revision??1)};const changes=[{id:crypto.randomUUID(),transactionId:t.id,fieldName:"__entity__",oldValue:null,newValue:payload},...Object.entries(payload??{}).map(([fieldName,newValue])=>({id:crypto.randomUUID(),transactionId:t.id,fieldName,oldValue:null,newValue}))];const{error}=await db.rpc("apply_taskmap_workspace_transaction",{p_workspace_id:workspaceId,p_transaction:t,p_changes:changes});if(error)throw error;}
async function pages(table:string,select:string,workspaceId:string,configure?:(q:any)=>any){const out:any[]=[];for(let from=0;;from+=1000){let q:any=db.from(table).select(select).eq("workspace_id",workspaceId).range(from,from+999);if(configure)q=configure(q);const{data,error}=await q;if(error)throw error;out.push(...(data??[]));if((data??[]).length<1000)break;}return out;}
async function sync(body:any,raw:string|null){const a=await authKey(raw),deviceId=String(body.deviceId??"");if(!/^[0-9a-f-]{36}$/i.test(deviceId))throw new Error("Valid device ID required");const boot=Array.isArray(body.bootstrapEntities)?body.bootstrapEntities.slice(0,5000):[],txs=Array.isArray(body.transactions)?body.transactions.slice(0,5000):[];if(a.role==="viewer"&&(boot.length||txs.length))throw new Error("This Sync Key is view-only");const{count,error:ce}=await db.from("workspace_sync_entities").select("entity_id",{count:"exact",head:true}).eq("workspace_id",a.workspaceId);if(ce)throw ce;let bootstrapped=0;if((count??0)===0){for(const item of boot){if(!item||typeof item!=="object"||!/^[0-9a-f-]{36}$/i.test(String(item.entityId??""))||!["task","task_layout","project","task_category","dev_backlog","task_template"].includes(String(item.entityType??"")))continue;await snap(a.workspaceId,deviceId,item);bootstrapped++;}}
let pushed=0;for(const item of txs){if(!item?.transaction?.id)continue;const{error}=await db.rpc("apply_taskmap_workspace_transaction",{p_workspace_id:a.workspaceId,p_transaction:item.transaction,p_changes:Array.isArray(item.changes)?item.changes:[]});if(error)throw error;pushed++;}
const now=new Date().toISOString();await db.from("workspace_devices").upsert({workspace_id:a.workspaceId,id:deviceId,name:String(body.deviceName??"TaskMap device").slice(0,80),last_seen_at:now,last_pull_at:now},{onConflict:"workspace_id,id"});
const entities=await pages("workspace_sync_entities","entity_type,entity_id,payload,is_deleted,revision,updated_at",a.workspaceId,q=>q.order("updated_at").order("entity_id"));const cursor=typeof body.cursor==="string"&&body.cursor?body.cursor:null;const remote=await pages("workspace_transactions","id,entity_type,entity_id,action_type,group_id,device_id,client_timestamp,server_received_timestamp,base_revision,result_revision",a.workspaceId,q=>{let z=q.order("server_received_timestamp").order("id");return cursor?z.gte("server_received_timestamp",cursor):z;});let changes:any[]=[];for(let i=0;i<remote.length;i+=200){const ids=remote.slice(i,i+200).map((x:any)=>x.id);if(!ids.length)continue;const{data,error}=await db.from("workspace_transaction_changes").select("id,transaction_id,field_name,old_value,new_value").eq("workspace_id",a.workspaceId).in("transaction_id",ids);if(error)throw error;changes.push(...(data??[]));}
const next=remote.length?String(remote.at(-1).server_received_timestamp):cursor??now;return{workspace:{id:a.workspace.id,name:a.workspace.name,recoveryEmailHint:a.workspace.recovery_email_hint??a.workspace.pending_recovery_email_hint,recoveryEmailVerified:Boolean(a.workspace.recovery_email_verified_at),role:a.role},entityCount:entities.length,bootstrapped,pushed,entities,transactions:remote,changes,cursor:next,syncedAt:now};}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return bad("POST required",405);if(!url||!service)return bad("TaskMap cloud is not configured",500);try{const body=await req.json().catch(()=>({})),action=String(body.action??""),key=req.headers.get("x-taskmap-sync-key"),rt=req.headers.get("x-taskmap-recovery-token");
if(action==="create_workspace"){const name=String(body.name??"").trim().slice(0,80);if(!name)return bad("Workspace name is required");const e=email(body.recoveryEmail),ph=e?await hash(e):null,pi=e?hint(e):null;const{data,error}=await db.from("sync_workspaces").insert({name,pending_recovery_email_hash:ph,pending_recovery_email_hint:pi}).select("id,name,created_at,updated_at").single();if(error||!data)throw error??new Error("Unable to create workspace");return ok({workspace:{...data,recoveryEmailHint:pi,recoveryEmailVerified:false,role:"owner"},...await newKey(data.id)});}
if(action==="workspace_info"){const a=await authKey(key),{count,error}=await db.from("workspace_sync_entities").select("entity_id",{count:"exact",head:true}).eq("workspace_id",a.workspaceId);if(error)throw error;return ok({workspace:{id:a.workspace.id,name:a.workspace.name,recoveryEmailHint:a.workspace.recovery_email_hint??a.workspace.pending_recovery_email_hint,recoveryEmailVerified:Boolean(a.workspace.recovery_email_verified_at),role:a.role},entityCount:count??0});}
if(action==="sync")return ok(await sync(body,key));
if(action==="rename_workspace"){const a=await authKey(key,true),name=String(body.name??"").trim().slice(0,80);if(!name)return bad("Workspace name is required");const{error}=await db.from("sync_workspaces").update({name,updated_at:new Date().toISOString()}).eq("id",a.workspaceId);if(error)throw error;return ok({workspace:{...(await workspace(a.workspaceId)),role:a.role}});}
if(action==="set_recovery_email"){const a=await authKey(key,true),e=email(body.email);if(!e||!e.includes("@"))return bad("Valid recovery email required");const h=await hash(e),i=hint(e),{error}=await db.from("sync_workspaces").update({pending_recovery_email_hash:h,pending_recovery_email_hint:i,recovery_email_hash:null,recovery_email_hint:null,recovery_email_verified_at:null,updated_at:new Date().toISOString()}).eq("id",a.workspaceId);if(error)throw error;return ok({recoveryEmailHint:i,recoveryEmailVerified:false});}
if(action==="clear_recovery_email"){const a=await authKey(key,true),{error}=await db.from("sync_workspaces").update({pending_recovery_email_hash:null,pending_recovery_email_hint:null,recovery_email_hash:null,recovery_email_hint:null,recovery_email_verified_at:null,updated_at:new Date().toISOString()}).eq("id",a.workspaceId);if(error)throw error;return ok({recoveryEmailHint:null,recoveryEmailVerified:false});}
if(action==="verify_recovery_email"){const a=await authKey(key,true),u=await recoveryUser(rt),h=await hash(email(u.email)),{data:w,error}=await db.from("sync_workspaces").select("pending_recovery_email_hash,pending_recovery_email_hint").eq("id",a.workspaceId).single();if(error||!w)throw error??new Error("Workspace not found");if(!w.pending_recovery_email_hash||!same(h,String(w.pending_recovery_email_hash)))return bad("This email does not match the pending recovery email",403);const now=new Date().toISOString(),{error:ue}=await db.from("sync_workspaces").update({recovery_email_hash:w.pending_recovery_email_hash,recovery_email_hint:w.pending_recovery_email_hint,recovery_email_verified_at:now,pending_recovery_email_hash:null,pending_recovery_email_hint:null,updated_at:now}).eq("id",a.workspaceId);if(ue)throw ue;return ok({recoveryEmailHint:w.pending_recovery_email_hint,recoveryEmailVerified:true});}
if(action==="recovery_list"){const u=await recoveryUser(rt),h=await hash(email(u.email)),{data,error}=await db.from("sync_workspaces").select("id,name,recovery_email_hint,updated_at").eq("recovery_email_hash",h).not("recovery_email_verified_at","is",null).order("name");if(error)throw error;return ok({workspaces:(data??[]).map(x=>({id:x.id,name:x.name,recoveryEmailHint:x.recovery_email_hint,updatedAt:x.updated_at}))});}
if(action==="recovery_new_key"){const u=await recoveryUser(rt),id=String(body.workspaceId??"");if(!/^[0-9a-f-]{36}$/i.test(id))return bad("Workspace ID required");const h=await hash(email(u.email)),{data:w,error}=await db.from("sync_workspaces").select("id,name,recovery_email_hash,recovery_email_verified_at,recovery_email_hint").eq("id",id).single();if(error||!w)throw error??new Error("Workspace not found");if(!w.recovery_email_verified_at||!w.recovery_email_hash||!same(h,String(w.recovery_email_hash)))return bad("Recovery email is not authorized for this workspace",403);return ok({workspace:{id:w.id,name:w.name,recoveryEmailHint:w.recovery_email_hint,recoveryEmailVerified:true,role:"owner"},...await newKey(id,"owner","Recovered key")});}
if(action==="rotate_key"){const a=await authKey(key,true),k=await newKey(a.workspaceId,"owner","Rotated key");await db.from("sync_workspace_keys").update({revoked_at:new Date().toISOString()}).eq("workspace_id",a.workspaceId).eq("id",a.keyId);return ok({workspace:{id:a.workspace.id,name:a.workspace.name},...k});}
return bad("Unknown action",404);}catch(cause){const m=cause instanceof Error?cause.message:String(cause);return bad(m,/Sync Key|Owner Sync Key|Recovery/.test(m)?401:500);}});
