import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const url=Deno.env.get("SUPABASE_URL")??"", service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-taskmap-api-key,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json","Cache-Control":"no-store"};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors});
const uuid=(value:unknown)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value??""));
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function safeEq(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function auth(req:Request){const h=req.headers.get("authorization"), raw=h?.toLowerCase().startsWith("bearer ")?h.slice(7).trim():req.headers.get("x-taskmap-api-key")?.trim()??"";const parts=raw.split(".");if(parts.length!==3||parts[0]!=="TMAPI1"||!uuid(parts[1])||parts[2].length<32)throw new Error("Invalid TaskMap API key");const{data:key,error}=await db.from("workspace_api_keys").select("workspace_id,id,key_hash,scopes").eq("id",parts[1]).is("revoked_at",null).single();if(error||!key)throw new Error("API key not found or revoked");if(!safeEq(await sha256(parts[2]),String(key.key_hash)))throw new Error("Invalid TaskMap API key");const scopes=Array.isArray(key.scopes)?key.scopes.map(String):[];if(!scopes.includes("write"))throw new Error("This API key is read-only");await db.from("workspace_api_keys").update({last_used_at:new Date().toISOString()}).eq("id",key.id).eq("workspace_id",key.workspace_id);return{workspaceId:String(key.workspace_id),keyId:String(key.id)};}
type Row={entity_id:string;payload:any;is_deleted:boolean;revision:number};
async function rows(workspaceId:string,type:"task"|"project"){const out:Row[]=[];for(let from=0;;from+=1000){const{data,error}=await db.from("workspace_sync_entities").select("entity_id,payload,is_deleted,revision").eq("workspace_id",workspaceId).eq("entity_type",type).range(from,from+999);if(error)throw error;out.push(...((data??[]) as Row[]));if((data??[]).length<1000)break;}return out;}
async function apply(workspaceId:string,keyId:string,type:"task"|"project",entityId:string,actionType:string,before:any,patch:Record<string,unknown>|null,groupId:string){const current=(await rows(workspaceId,type)).find(row=>row.entity_id===entityId);if(!current?.payload||current.is_deleted&&patch===null)return;const now=new Date().toISOString(), txId=crypto.randomUUID(), base=Number(current.revision??before?.revision??0);const changes=patch===null?[{id:crypto.randomUUID(),transactionId:txId,fieldName:"__entity__",oldValue:before,newValue:null}]:Object.entries(patch).filter(([fieldName,newValue])=>JSON.stringify(before[fieldName])!==JSON.stringify(newValue)).map(([fieldName,newValue])=>({id:crypto.randomUUID(),transactionId:txId,fieldName,oldValue:before[fieldName]??null,newValue}));if(!changes.length)return;const transaction={id:txId,entityType:type,entityId,actionType,groupId,deviceId:keyId,clientTimestamp:now,baseRevision:base,resultRevision:base+1};const{error}=await db.rpc("apply_taskmap_workspace_transaction",{p_workspace_id:workspaceId,p_transaction:transaction,p_changes:changes});if(error)throw error;}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"POST required"},405);try{const a=await auth(req),body=await req.json().catch(()=>({})),projectId=String(body.projectId??"");if(!uuid(projectId))return json({ok:false,error:"projectId must be a UUID"},400);const taskMode=body.taskMode==="cascade"?"cascade":"detach";const projectRows=await rows(a.workspaceId,"project"),project=projectRows.find(row=>row.entity_id===projectId);if(!project?.payload||project.is_deleted)return json({ok:false,error:"Project not found"},404);const taskRows=await rows(a.workspaceId,"task"),allTasks=taskRows.filter(row=>row.payload).map(row=>row.payload),tasks=taskRows.filter(row=>row.payload&&!row.is_deleted).map(row=>row.payload);const assigned=allTasks.filter(task=>task.projectId===projectId),activeAssigned=tasks.filter(task=>task.projectId===projectId),affected=new Set<string>(activeAssigned.map(task=>String(task.id)));if(taskMode==="cascade"){const queue=[...affected];while(queue.length){const parentId=queue.shift()!;for(const child of tasks.filter(task=>task.parentTaskId===parentId)){if(affected.has(String(child.id)))continue;affected.add(String(child.id));queue.push(String(child.id));}}}const now=new Date().toISOString(),groupId=crypto.randomUUID();if(taskMode==="detach"){for(const task of assigned)await apply(a.workspaceId,a.keyId,"task",String(task.id),"API_TASK_DETACHED_BY_PROJECT_DELETE",task,{projectId:null,updatedAt:now,revision:Number(task.revision??0)+1},groupId);}else{for(const id of affected){const task=tasks.find(candidate=>String(candidate.id)===id);if(!task||task.deletedAt)continue;const patch:Record<string,unknown>={deletedAt:now,updatedAt:now,revision:Number(task.revision??0)+1};if(task.projectId===projectId)patch.projectId=null;await apply(a.workspaceId,a.keyId,"task",id,task.projectId===projectId?"API_TASK_DELETED_WITH_PROJECT":"API_TASK_DELETED_WITH_PROJECT_DESCENDANT",task,patch,groupId);}}await apply(a.workspaceId,a.keyId,"project",projectId,taskMode==="cascade"?"API_PROJECT_DELETED_WITH_TASKS":"API_PROJECT_DELETED_KEEP_TASKS",project.payload,null,groupId);return json({ok:true,data:{projectId,taskMode,assignedTasks:assigned.length,affectedTasks:affected.size}});}catch(cause){const message=cause instanceof Error?cause.message:String(cause);return json({ok:false,error:message},/read-only/.test(message)?403:/API key|revoked/.test(message)?401:400);}});
